hardware:
  # mode: "strong"
  mode: "weak"

paths:
  data_path: "..//lyft-motion-prediction-autonomous-vehicles"
  output_data: "./"
  log_output: "logs_output"
  images_output: "images"

processing:
  batch_size:
    weak: 1000
    strong: 10000
  sample_rate:
    weak: 0.005
    strong: 0.01

raster_params:
  raster_size:
    weak: [512, 512]
    strong: [4200, 4200]
  pixel_size:
    weak: [0.1, 0.1]
    strong: [0.05, 0.05]
  ego_center: [0.5, 0.5]
  map_type: "py_semantic"
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "..//lyft-motion-prediction-autonomous-vehicles/semantic_map/semantic_map.pb"
  dataset_meta_key: "..//lyft-motion-prediction-autonomous-vehicles/meta.json"
  set_origin_to_bottom: False
  filter_agents_threshold: 0.9
  disable_traffic_light_faces: False

model_params:
  history_num_frames: 10
  future_num_frames: 50
  train_epochs:
    weak: 5
    strong: 10
  model_architecture: "resnet18"
  load_model: False
  model_path: "model.pth"
  lr: 1e-3
  weight_decay: 1e-5
  render_ego_history: True
  step_time: 0.1

visualization:
  bins:
    weak: 30
    strong: 50

data_loaders:
  train:
    key: "..//lyft-motion-prediction-autonomous-vehicles/scenes/train.zarr"
    batch_size: 16
    shuffle: True
    num_workers: 4
  validation:
    key: "..//lyft-motion-prediction-autonomous-vehicles/scenes/validate.zarr"
    batch_size: 16
    shuffle: False
    num_workers: 4
  test:
    key: "..//lyft-motion-prediction-autonomous-vehicles/scenes/test.zarr"
    batch_size: 16
    shuffle: False
    num_workers: 4

training_params:
  batch_size: 64
  shuffle: True
  num_workers: 2
  optimizer: "adam"
  scheduler: "step"
