hardware:
  mode: "weak"
  # mode: "strong"

data_path: "../lyft-motion-prediction-autonomous-vehicles"

train_data_loader:
  key:
    weak: "../lyft-motion-prediction-autonomous-vehicles/scenes/sample.zarr"
    strong: "../lyft-motion-prediction-autonomous-vehicles/scenes/train.zarr"
  batch_size:
    weak: 4
    strong: 8
  shuffle: True
  num_workers:
    weak: 2
    strong: 2

val_data_loader:
  key: "../lyft-motion-prediction-autonomous-vehicles/scenes/validate.zarr"
  batch_size: 16
  shuffle: False
  num_workers: 4

test_data_loader:
  key: 
    weak: "../lyft-motion-prediction-autonomous-vehicles/scenes/test.zarr"
    strong: "../lyft-motion-prediction-autonomous-vehicles/scenes/test.zarr"
  batch_size:
    weak: 4
    strong: 16
  shuffle: False
  num_workers:
    weak: 2
    strong: 4

# sample_data_loader:
#   key: "../lyft-motion-prediction-autonomous-vehicles/scenes/sample.zarr"
#   batch_size: 16
#   shuffle: False
#   num_workers: 4

raster_params:
  raster_size:
    weak: [112, 112]
    strong: [224, 224]
  pixel_size: [0.25, 0.25]
  ego_center: [0.25, 0.5]
  map_type: "py_semantic"
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "../lyft-motion-prediction-autonomous-vehicles/semantic_map/semantic_map.pb"
  dataset_meta_key: "../lyft-motion-prediction-autonomous-vehicles/meta.json"
  set_origin_to_bottom: False
  filter_agents_threshold: 0.5
  disable_traffic_light_faces: False
  use_traffic_lights: True

model_params:
  history_num_frames: 10
  future_num_frames: 50
  # future_num_frames: 150
  num_modes: 3
  train_epochs:
    weak: 2
    strong: 10
  model_architecture: "resnet18"
  load_model: False
  model_path: "model.pth"
  lr: 0.001
  weight_decay: 0.00001
  render_ego_history: True
  step_time: 0.1

training_params:
  # batch_size: 64  # Размер батча
  batch_size: 8  # Размер батча
  shuffle: True  # Перемешивание данных при обучении
  num_workers: 4  # Количество потоков загрузки данных
  optimizer: "adam"  # Оптимизатор (Adam)
  scheduler: "step"  # Планировщик скорости обучения

loss_params:
  lambda_smooth: 0.5
  lambda_entropy: 0.01
  lambda_coverage: 0.05

paths:
  output_data: "output_data/"
