hardware:
  mode: "strong"

paths:
  data_path: "../lyft-motion-prediction-autonomous-vehicles"
  output_data: "./"
  log_output: "logs_output"
  images_output: "images"

processing:
  batch_size:
    weak: 1000
    strong: 10000
  sample_rate:
    weak: 0.005
    strong: 0.01

raster_params:
  raster_size:
    weak: [224, 224]
    strong: [4200, 4200]
  pixel_size:
    weak: [0.5, 0.5]
    strong: [0.05, 0.05]
  ego_center: [0.25, 0.5]

model_params:
  history_num_frames: 10
  future_num_frames: 50
  train_epochs:
    weak: 5
    strong: 10

visualization:
  bins:
    weak: 30
    strong: 50
